### ISSUE TITLE
Rename 'metric' config key to conform to the metrics module naming

### ISSUE THREAD

**Issue by archaron** [im-kulikov/helium#100]
It is not obvious, why the config key is named as 'metric' instead of logically correct (IMHO) 'metrics'.
[https://github.com/im-kulikov/helium/blob/0a5977eb301dca4f90f06ef03a77b779eedad92e/web/servers.go#L83](https://github.com/im-kulikov/helium/blob/0a5977eb301dca4f90f06ef03a77b779eedad92e/web/servers.go#L83)

I suggest renaming it to conform to the module naming. This will help to avoid future misunderstands and mistakes in config files.

**Comment by im-kulikov** [comment]
@archaron thx for the issue, pls take a look at ops-server (`web.OpsModule`) it will replace the next servers with endpoints
- metrics
- profile

In the future, I propose to drop `web.ProfilerModule` and `web.MetricsModule`.
