### ISSUE TITLE
Catch errors

### ISSUE THREAD

**Issue by jenchik** [im-kulikov/helium#13]
When using Catch we may lose errors report of service in ELK, Splunk etc.

Called Catch as method for structure of Settings.

**Comment by im-kulikov** [comment]
@jenchik oh.. thanks for report.. I will think about how to solve the problem you described.

**Comment by jenchik** [comment]
Call Catch can be considered for entire instance. Then Name and BuildVersion make global for the Helium package. And initialize them from main.Init
